version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    # environment:
    #   - DATABASE_HOST=db
    #   - DATABASE_USER=root
    #   - DATABASE_PASSWORD=
    #   - DATABASE_NAME=suruchi
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD=
      MYSQL_DATABASE=suruchi
    ports:
      - "3306:3306"