version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"