version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    # env_file:
    #   - .env
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_NAME=mydatabase

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'root' # ${DATABASE_NAME}
      # MYSQL_USER: ${DATABASE_USER}
      # MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"